USE [master]
GO
CREATE DATABASE Banking 
GO
ALTER DATABASE Banking SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Banking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE Banking SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE Banking SET ANSI_NULLS OFF 
GO
ALTER DATABASE Banking SET ANSI_PADDING OFF 
GO
ALTER DATABASE Banking SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE Banking SET ARITHABORT OFF 
GO
ALTER DATABASE Banking SET AUTO_CLOSE OFF 
GO
ALTER DATABASE Banking SET AUTO_SHRINK OFF 
GO
ALTER DATABASE Banking SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE Banking SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE Banking SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE Banking SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE Banking SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE Banking SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE Banking SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE Banking SET  DISABLE_BROKER 
GO
ALTER DATABASE Banking SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE Banking SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE Banking SET TRUSTWORTHY OFF 
GO
ALTER DATABASE Banking SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE Banking SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE Banking SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE Banking SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE Banking SET RECOVERY FULL 
GO
ALTER DATABASE Banking SET  MULTI_USER 
GO
ALTER DATABASE Banking SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE Banking SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Banking', N'ON'
GO
USE [Banking]
GO
/****** Object:  Table [dbo].[employeetab]    Script Date: 15.12.2015 13:45:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Accounts](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [nvarchar](50) NOT NULL,
	[AccountName] [nvarchar](50) NOT NULL,
	[Balance] [numeric](18,2) NULL,
	[empimage] [image] NULL,
	[Password] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Accounts] PRIMARY KEY CLUSTERED 
(
	[AccountNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[Accounts] ON 


SET IDENTITY_INSERT [dbo].[Accounts] OFF


CREATE TABLE [dbo].[Transfers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TransferFrom] [nvarchar](50) NOT NULL,
	[TransferTo] [nvarchar](50) NOT NULL,
	[Amount] [numeric](18, 2) NULL,
	[DateCreated] [datetime] NULL,
)

GO

CREATE TABLE [dbo].[Deposits](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [nvarchar](50) NOT NULL,
	[Amount] [numeric](18, 2) NULL,
	[DateCreated] [datetime] NULL,
)

GO



CREATE TABLE [dbo].[Withdraws](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [nvarchar](50) NOT NULL,
	[Amount] [numeric](18, 2) NULL,
	[DateCreated] [datetime] NULL,
)

GO
